// Traductions des lieux : pays, villes et départements français.
export const GEO_TRANSLATIONS: Record<string, { en: string; ar: string }> = {
  // ---------- Pays ----------
  "Afghanistan": { en: "Afghanistan", ar: "أفغانستان" },
  "Afrique du Sud": { en: "South Africa", ar: "جنوب أفريقيا" },
  "Albanie": { en: "Albania", ar: "ألبانيا" },
  "Algérie": { en: "Algeria", ar: "الجزائر" },
  "Allemagne": { en: "Germany", ar: "ألمانيا" },
  "Andorre": { en: "Andorra", ar: "أندورا" },
  "Angola": { en: "Angola", ar: "أنغولا" },
  "Arabie saoudite": { en: "Saudi Arabia", ar: "السعودية" },
  "Argentine": { en: "Argentina", ar: "الأرجنتين" },
  "Arménie": { en: "Armenia", ar: "أرمينيا" },
  "Australie": { en: "Australia", ar: "أستراليا" },
  "Autriche": { en: "Austria", ar: "النمسا" },
  "Azerbaïdjan": { en: "Azerbaijan", ar: "أذربيجان" },
  "Bahreïn": { en: "Bahrain", ar: "البحرين" },
  "Bangladesh": { en: "Bangladesh", ar: "بنغلاديش" },
  "Belgique": { en: "Belgium", ar: "بلجيكا" },
  "Bénin": { en: "Benin", ar: "بنين" },
  "Biélorussie": { en: "Belarus", ar: "بيلاروسيا" },
  "Bolivie": { en: "Bolivia", ar: "بوليفيا" },
  "Bosnie-Herzégovine": { en: "Bosnia and Herzegovina", ar: "البوسنة والهرسك" },
  "Botswana": { en: "Botswana", ar: "بوتسوانا" },
  "Brésil": { en: "Brazil", ar: "البرازيل" },
  "Brunei": { en: "Brunei", ar: "بروناي" },
  "Bulgarie": { en: "Bulgaria", ar: "بلغاريا" },
  "Burkina Faso": { en: "Burkina Faso", ar: "بوركينا فاسو" },
  "Burundi": { en: "Burundi", ar: "بوروندي" },
  "Cambodge": { en: "Cambodia", ar: "كمبوديا" },
  "Cameroun": { en: "Cameroon", ar: "الكاميرون" },
  "Canada": { en: "Canada", ar: "كندا" },
  "Cap-Vert": { en: "Cape Verde", ar: "الرأس الأخضر" },
  "Chili": { en: "Chile", ar: "تشيلي" },
  "Chine": { en: "China", ar: "الصين" },
  "Chypre": { en: "Cyprus", ar: "قبرص" },
  "Colombie": { en: "Colombia", ar: "كولومبيا" },
  "Comores": { en: "Comoros", ar: "جزر القمر" },
  "Congo": { en: "Congo", ar: "الكونغو" },
  "Congo (RDC)": { en: "DR Congo", ar: "جمهورية الكونغو الديمقراطية" },
  "Corée du Sud": { en: "South Korea", ar: "كوريا الجنوبية" },
  "Costa Rica": { en: "Costa Rica", ar: "كوستاريكا" },
  "Côte d'Ivoire": { en: "Ivory Coast", ar: "ساحل العاج" },
  "Croatie": { en: "Croatia", ar: "كرواتيا" },
  "Cuba": { en: "Cuba", ar: "كوبا" },
  "Danemark": { en: "Denmark", ar: "الدانمرك" },
  "Djibouti": { en: "Djibouti", ar: "جيبوتي" },
  "Égypte": { en: "Egypt", ar: "مصر" },
  "Émirats arabes unis": { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة" },
  "Équateur": { en: "Ecuador", ar: "الإكوادور" },
  "Érythrée": { en: "Eritrea", ar: "إريتريا" },
  "Espagne": { en: "Spain", ar: "إسبانيا" },
  "Estonie": { en: "Estonia", ar: "إستونيا" },
  "Eswatini": { en: "Eswatini", ar: "إسواتيني" },
  "États-Unis": { en: "United States", ar: "الولايات المتحدة" },
  "Éthiopie": { en: "Ethiopia", ar: "إثيوبيا" },
  "Finlande": { en: "Finland", ar: "فنلندا" },
  "France": { en: "France", ar: "فرنسا" },
  "Gabon": { en: "Gabon", ar: "الغابون" },
  "Gambie": { en: "Gambia", ar: "غامبيا" },
  "Géorgie": { en: "Georgia", ar: "جورجيا" },
  "Ghana": { en: "Ghana", ar: "غانا" },
  "Grèce": { en: "Greece", ar: "اليونان" },
  "Guinée": { en: "Guinea", ar: "غينيا" },
  "Guinée-Bissau": { en: "Guinea-Bissau", ar: "غينيا بيساو" },
  "Guyana": { en: "Guyana", ar: "غيانا" },
  "Haïti": { en: "Haiti", ar: "هايتي" },
  "Honduras": { en: "Honduras", ar: "هندوراس" },
  "Hongrie": { en: "Hungary", ar: "هنغاريا" },
  "Île Maurice": { en: "Mauritius", ar: "موريشيوس" },
  "Inde": { en: "India", ar: "الهند" },
  "Indonésie": { en: "Indonesia", ar: "إندونيسيا" },
  "Irak": { en: "Iraq", ar: "العراق" },
  "Iran": { en: "Iran", ar: "إيران" },
  "Irlande": { en: "Ireland", ar: "أيرلندا" },
  "Islande": { en: "Iceland", ar: "آيسلندا" },
  "Israël": { en: "Israel", ar: "إسرائيل" },
  "Italie": { en: "Italy", ar: "إيطاليا" },
  "Jamaïque": { en: "Jamaica", ar: "جامايكا" },
  "Japon": { en: "Japan", ar: "اليابان" },
  "Jordanie": { en: "Jordan", ar: "الأردن" },
  "Kazakhstan": { en: "Kazakhstan", ar: "كازاخستان" },
  "Kenya": { en: "Kenya", ar: "كينيا" },
  "Kirghizistan": { en: "Kyrgyzstan", ar: "قيرغيزستان" },
  "Koweït": { en: "Kuwait", ar: "الكويت" },
  "Laos": { en: "Laos", ar: "لاوس" },
  "Lesotho": { en: "Lesotho", ar: "ليسوتو" },
  "Lettonie": { en: "Latvia", ar: "لاتفيا" },
  "Liban": { en: "Lebanon", ar: "لبنان" },
  "Libéria": { en: "Liberia", ar: "ليبيريا" },
  "Libye": { en: "Libya", ar: "ليبيا" },
  "Liechtenstein": { en: "Liechtenstein", ar: "ليختنشتاين" },
  "Lituanie": { en: "Lithuania", ar: "ليتوانيا" },
  "Luxembourg": { en: "Luxembourg", ar: "لوكسمبورغ" },
  "Macédoine du Nord": { en: "North Macedonia", ar: "مقدونيا الشمالية" },
  "Madagascar": { en: "Madagascar", ar: "مدغشقر" },
  "Malaisie": { en: "Malaysia", ar: "ماليزيا" },
  "Malawi": { en: "Malawi", ar: "ملاوي" },
  "Maldives": { en: "Maldives", ar: "جزر المالديف" },
  "Mali": { en: "Mali", ar: "مالي" },
  "Malte": { en: "Malta", ar: "مالطا" },
  "Maroc": { en: "Morocco", ar: "المغرب" },
  "Mauritanie": { en: "Mauritania", ar: "موريتانيا" },
  "Mexique": { en: "Mexico", ar: "المكسيك" },
  "Moldavie": { en: "Moldova", ar: "مولدوفا" },
  "Monaco": { en: "Monaco", ar: "موناكو" },
  "Mongolie": { en: "Mongolia", ar: "منغوليا" },
  "Monténégro": { en: "Montenegro", ar: "الجبل الأسود" },
  "Mozambique": { en: "Mozambique", ar: "موزمبيق" },
  "Myanmar": { en: "Myanmar", ar: "ميانمار" },
  "Namibie": { en: "Namibia", ar: "ناميبيا" },
  "Népal": { en: "Nepal", ar: "نيبال" },
  "Nicaragua": { en: "Nicaragua", ar: "نيكاراغوا" },
  "Niger": { en: "Niger", ar: "النيجر" },
  "Nigéria": { en: "Nigeria", ar: "نيجيريا" },
  "Norvège": { en: "Norway", ar: "النرويج" },
  "Nouvelle-Zélande": { en: "New Zealand", ar: "نيوزيلندا" },
  "Oman": { en: "Oman", ar: "عُمان" },
  "Ouganda": { en: "Uganda", ar: "أوغندا" },
  "Ouzbékistan": { en: "Uzbekistan", ar: "أوزبكستان" },
  "Pakistan": { en: "Pakistan", ar: "باكستان" },
  "Palestine": { en: "Palestine", ar: "فلسطين" },
  "Panama": { en: "Panama", ar: "بنما" },
  "Paraguay": { en: "Paraguay", ar: "باراغواي" },
  "Pays-Bas": { en: "Netherlands", ar: "هولندا" },
  "Pérou": { en: "Peru", ar: "البيرو" },
  "Philippines": { en: "Philippines", ar: "الفلبين" },
  "Pologne": { en: "Poland", ar: "بولندا" },
  "Portugal": { en: "Portugal", ar: "البرتغال" },
  "Qatar": { en: "Qatar", ar: "قطر" },
  "République dominicaine": { en: "Dominican Republic", ar: "جمهورية الدومينيكان" },
  "République tchèque": { en: "Czech Republic", ar: "التشيك" },
  "Roumanie": { en: "Romania", ar: "رومانيا" },
  "Royaume-Uni": { en: "United Kingdom", ar: "المملكة المتحدة" },
  "Russie": { en: "Russia", ar: "روسيا" },
  "Rwanda": { en: "Rwanda", ar: "رواندا" },
  "Saint-Marin": { en: "San Marino", ar: "سان مارينو" },
  "Salvador": { en: "El Salvador", ar: "السلفادور" },
  "Sénégal": { en: "Senegal", ar: "السنغال" },
  "Serbie": { en: "Serbia", ar: "صربيا" },
  "Seychelles": { en: "Seychelles", ar: "سيشل" },
  "Sierra Leone": { en: "Sierra Leone", ar: "سيراليون" },
  "Singapour": { en: "Singapore", ar: "سنغافورة" },
  "Slovaquie": { en: "Slovakia", ar: "سلوفاكيا" },
  "Slovénie": { en: "Slovenia", ar: "سلوفينيا" },
  "Somalie": { en: "Somalia", ar: "الصومال" },
  "Soudan": { en: "Sudan", ar: "السودان" },
  "Sri Lanka": { en: "Sri Lanka", ar: "سريلانكا" },
  "Suède": { en: "Sweden", ar: "السويد" },
  "Suisse": { en: "Switzerland", ar: "سويسرا" },
  "Suriname": { en: "Suriname", ar: "سورينام" },
  "Syrie": { en: "Syria", ar: "سوريا" },
  "Tadjikistan": { en: "Tajikistan", ar: "طاجيكستان" },
  "Tanzanie": { en: "Tanzania", ar: "تنزانيا" },
  "Tchad": { en: "Chad", ar: "تشاد" },
  "Thaïlande": { en: "Thailand", ar: "تايلاند" },
  "Togo": { en: "Togo", ar: "توغو" },
  "Trinité-et-Tobago": { en: "Trinidad and Tobago", ar: "ترينيداد وتوباغو" },
  "Tunisie": { en: "Tunisia", ar: "تونس" },
  "Turkménistan": { en: "Turkmenistan", ar: "تركمانستان" },
  "Turquie": { en: "Turkey", ar: "تركيا" },
  "Ukraine": { en: "Ukraine", ar: "أوكرانيا" },
  "Uruguay": { en: "Uruguay", ar: "أوروغواي" },
  "Venezuela": { en: "Venezuela", ar: "فنزويلا" },
  "Viêt Nam": { en: "Vietnam", ar: "فيتنام" },
  "Yémen": { en: "Yemen", ar: "اليمن" },
  "Zambie": { en: "Zambia", ar: "زامبيا" },
  "Zimbabwe": { en: "Zimbabwe", ar: "زيمبابوي" },

  // ---------- Villes ----------
  "Paris": { en: "Paris", ar: "باريس" },
  "Marseille": { en: "Marseille", ar: "مرسيليا" },
  "Lyon": { en: "Lyon", ar: "ليون" },
  "Toulouse": { en: "Toulouse", ar: "تولوز" },
  "Nice": { en: "Nice", ar: "نيس" },
  "Nantes": { en: "Nantes", ar: "نانت" },
  "Montpellier": { en: "Montpellier", ar: "مونبلييه" },
  "Strasbourg": { en: "Strasbourg", ar: "ستراسبورغ" },
  "Bordeaux": { en: "Bordeaux", ar: "بوردو" },
  "Lille": { en: "Lille", ar: "ليل" },
  "Rennes": { en: "Rennes", ar: "رين" },
  "Reims": { en: "Reims", ar: "ريمس" },
  "Saint-Étienne": { en: "Saint-Étienne", ar: "سانت إتيان" },
  "Toulon": { en: "Toulon", ar: "تولون" },
  "Le Havre": { en: "Le Havre", ar: "لوهافر" },
  "Grenoble": { en: "Grenoble", ar: "غرونوبل" },
  "Dijon": { en: "Dijon", ar: "ديجون" },
  "Angers": { en: "Angers", ar: "أنجيه" },
  "Nîmes": { en: "Nîmes", ar: "نيم" },
  "Villeurbanne": { en: "Villeurbanne", ar: "فيلوربان" },
  "Clermont-Ferrand": { en: "Clermont-Ferrand", ar: "كليرمون فيران" },
  "Aix-en-Provence": { en: "Aix-en-Provence", ar: "إكس أون بروفانس" },
  "Brest": { en: "Brest", ar: "بريست" },
  "Tours": { en: "Tours", ar: "تور" },
  "Amiens": { en: "Amiens", ar: "أميان" },
  "Limoges": { en: "Limoges", ar: "ليموج" },
  "Annecy": { en: "Annecy", ar: "أنسي" },
  "Perpignan": { en: "Perpignan", ar: "بربينيان" },
  "Metz": { en: "Metz", ar: "ميتز" },
  "Besançon": { en: "Besançon", ar: "بيزانسون" },
  "Orléans": { en: "Orléans", ar: "أورليان" },
  "Rouen": { en: "Rouen", ar: "روان" },
  "Mulhouse": { en: "Mulhouse", ar: "ميلوز" },
  "Caen": { en: "Caen", ar: "كاين" },
  "Nancy": { en: "Nancy", ar: "نانسي" },
  "Bruxelles": { en: "Brussels", ar: "بروكسل" },
  "Anvers": { en: "Antwerp", ar: "أنتويرب" },
  "Liège": { en: "Liège", ar: "لييج" },
  "Genève": { en: "Geneva", ar: "جنيف" },
  "Lausanne": { en: "Lausanne", ar: "لوزان" },
  "Zurich": { en: "Zurich", ar: "زيورخ" },
  "Montréal": { en: "Montreal", ar: "مونتريال" },
  "Londres": { en: "London", ar: "لندن" },
  "Madrid": { en: "Madrid", ar: "مدريد" },
  "Barcelone": { en: "Barcelona", ar: "برشلونة" },
  "Berlin": { en: "Berlin", ar: "برلين" },
  "Milan": { en: "Milan", ar: "ميلانو" },
  "Rome": { en: "Rome", ar: "روما" },
  "Casablanca": { en: "Casablanca", ar: "الدار البيضاء" },
  "Rabat": { en: "Rabat", ar: "الرباط" },
  "Marrakech": { en: "Marrakesh", ar: "مراكش" },
  "Alger": { en: "Algiers", ar: "الجزائر العاصمة" },
  "Oran": { en: "Oran", ar: "وهران" },
  "Tunis": { en: "Tunis", ar: "تونس العاصمة" },
  "Dakar": { en: "Dakar", ar: "داكار" },
  "Abidjan": { en: "Abidjan", ar: "أبيدجان" },
  "Istanbul": { en: "Istanbul", ar: "إسطنبول" },
  "Le Caire": { en: "Cairo", ar: "القاهرة" },
  "Dubaï": { en: "Dubai", ar: "دبي" },
  "Doha": { en: "Doha", ar: "الدوحة" },
  "Riyad": { en: "Riyadh", ar: "الرياض" },
  "Beyrouth": { en: "Beirut", ar: "بيروت" },

  // ---------- Départements français ----------
  "Ain": { en: "Ain", ar: "آن" },
  "Aisne": { en: "Aisne", ar: "إين" },
  "Allier": { en: "Allier", ar: "أليي" },
  "Alpes-de-Haute-Provence": { en: "Alpes-de-Haute-Provence", ar: "ألب دو أوت بروفانس" },
  "Hautes-Alpes": { en: "Hautes-Alpes", ar: "أوت ألب" },
  "Alpes-Maritimes": { en: "Alpes-Maritimes", ar: "الألب البحرية" },
  "Ardèche": { en: "Ardèche", ar: "أرديش" },
  "Ardennes": { en: "Ardennes", ar: "أردين" },
  "Ariège": { en: "Ariège", ar: "أرييج" },
  "Aube": { en: "Aube", ar: "أوب" },
  "Aude": { en: "Aude", ar: "أود" },
  "Aveyron": { en: "Aveyron", ar: "أفيرون" },
  "Bouches-du-Rhône": { en: "Bouches-du-Rhône", ar: "بوش دو رون" },
  "Calvados": { en: "Calvados", ar: "كالفادوس" },
  "Cantal": { en: "Cantal", ar: "كانتال" },
  "Charente": { en: "Charente", ar: "شارانت" },
  "Charente-Maritime": { en: "Charente-Maritime", ar: "شارانت البحرية" },
  "Cher": { en: "Cher", ar: "شير" },
  "Corrèze": { en: "Corrèze", ar: "كوريز" },
  "Corse-du-Sud": { en: "South Corsica", ar: "كورسيكا الجنوبية" },
  "Haute-Corse": { en: "Upper Corsica", ar: "كورسيكا العليا" },
  "Côte-d'Or": { en: "Côte-d'Or", ar: "كوت دور" },
  "Côtes-d'Armor": { en: "Côtes-d'Armor", ar: "كوت دارمور" },
  "Creuse": { en: "Creuse", ar: "كروز" },
  "Dordogne": { en: "Dordogne", ar: "دوردوني" },
  "Doubs": { en: "Doubs", ar: "دو" },
  "Drôme": { en: "Drôme", ar: "دروم" },
  "Eure": { en: "Eure", ar: "أور" },
  "Eure-et-Loir": { en: "Eure-et-Loir", ar: "أور إي لوار" },
  "Finistère": { en: "Finistère", ar: "فينيستير" },
  "Gard": { en: "Gard", ar: "غار" },
  "Haute-Garonne": { en: "Haute-Garonne", ar: "غارون العليا" },
  "Gers": { en: "Gers", ar: "جير" },
  "Gironde": { en: "Gironde", ar: "جيروند" },
  "Hérault": { en: "Hérault", ar: "إيرو" },
  "Ille-et-Vilaine": { en: "Ille-et-Vilaine", ar: "إيل إي فيلين" },
  "Indre": { en: "Indre", ar: "أندر" },
  "Indre-et-Loire": { en: "Indre-et-Loire", ar: "أندر إي لوار" },
  "Isère": { en: "Isère", ar: "إيزير" },
  "Jura": { en: "Jura", ar: "جورا" },
  "Landes": { en: "Landes", ar: "لاند" },
  "Loir-et-Cher": { en: "Loir-et-Cher", ar: "لوار إي شير" },
  "Loire": { en: "Loire", ar: "لوار" },
  "Haute-Loire": { en: "Haute-Loire", ar: "لوار العليا" },
  "Loire-Atlantique": { en: "Loire-Atlantique", ar: "لوار الأطلسية" },
  "Loiret": { en: "Loiret", ar: "لواريه" },
  "Lot": { en: "Lot", ar: "لو" },
  "Lot-et-Garonne": { en: "Lot-et-Garonne", ar: "لو إي غارون" },
  "Lozère": { en: "Lozère", ar: "لوزير" },
  "Maine-et-Loire": { en: "Maine-et-Loire", ar: "مين إي لوار" },
  "Manche": { en: "Manche", ar: "مانش" },
  "Marne": { en: "Marne", ar: "مارن" },
  "Haute-Marne": { en: "Haute-Marne", ar: "مارن العليا" },
  "Mayenne": { en: "Mayenne", ar: "مايين" },
  "Meurthe-et-Moselle": { en: "Meurthe-et-Moselle", ar: "مورت إي موزيل" },
  "Meuse": { en: "Meuse", ar: "موز" },
  "Morbihan": { en: "Morbihan", ar: "موربيهان" },
  "Moselle": { en: "Moselle", ar: "موزيل" },
  "Nièvre": { en: "Nièvre", ar: "نييفر" },
  "Nord": { en: "Nord", ar: "نور" },
  "Oise": { en: "Oise", ar: "واز" },
  "Orne": { en: "Orne", ar: "أورن" },
  "Pas-de-Calais": { en: "Pas-de-Calais", ar: "با دو كاليه" },
  "Puy-de-Dôme": { en: "Puy-de-Dôme", ar: "بوي دو دوم" },
  "Pyrénées-Atlantiques": { en: "Pyrénées-Atlantiques", ar: "البرانس الأطلسية" },
  "Hautes-Pyrénées": { en: "Hautes-Pyrénées", ar: "البرانس العليا" },
  "Pyrénées-Orientales": { en: "Pyrénées-Orientales", ar: "البرانس الشرقية" },
  "Bas-Rhin": { en: "Bas-Rhin", ar: "الراين السفلى" },
  "Haut-Rhin": { en: "Haut-Rhin", ar: "الراين العليا" },
  "Rhône": { en: "Rhône", ar: "رون" },
  "Haute-Saône": { en: "Haute-Saône", ar: "سون العليا" },
  "Saône-et-Loire": { en: "Saône-et-Loire", ar: "سون إي لوار" },
  "Sarthe": { en: "Sarthe", ar: "سارت" },
  "Savoie": { en: "Savoie", ar: "سافوا" },
  "Haute-Savoie": { en: "Haute-Savoie", ar: "سافوا العليا" },
  "Seine-Maritime": { en: "Seine-Maritime", ar: "السين البحرية" },
  "Seine-et-Marne": { en: "Seine-et-Marne", ar: "سين إي مارن" },
  "Yvelines": { en: "Yvelines", ar: "إيفلين" },
  "Deux-Sèvres": { en: "Deux-Sèvres", ar: "دو سيفر" },
  "Somme": { en: "Somme", ar: "السوم" },
  "Tarn": { en: "Tarn", ar: "تارن" },
  "Tarn-et-Garonne": { en: "Tarn-et-Garonne", ar: "تارن إي غارون" },
  "Var": { en: "Var", ar: "فار" },
  "Vaucluse": { en: "Vaucluse", ar: "فوكلوز" },
  "Vendée": { en: "Vendée", ar: "فانديه" },
  "Vienne": { en: "Vienne", ar: "فيين" },
  "Haute-Vienne": { en: "Haute-Vienne", ar: "فيين العليا" },
  "Vosges": { en: "Vosges", ar: "فوج" },
  "Yonne": { en: "Yonne", ar: "يون" },
  "Territoire de Belfort": { en: "Territoire de Belfort", ar: "إقليم بلفور" },
  "Essonne": { en: "Essonne", ar: "إيسون" },
  "Hauts-de-Seine": { en: "Hauts-de-Seine", ar: "أو دو سين" },
  "Seine-Saint-Denis": { en: "Seine-Saint-Denis", ar: "سين سان دوني" },
  "Val-de-Marne": { en: "Val-de-Marne", ar: "فال دو مارن" },
  "Val-d'Oise": { en: "Val-d'Oise", ar: "فال دواز" },
  "Guadeloupe": { en: "Guadeloupe", ar: "غوادلوب" },
  "Martinique": { en: "Martinique", ar: "مارتينيك" },
  "Guyane": { en: "French Guiana", ar: "غويانا الفرنسية" },
  "La Réunion": { en: "Réunion", ar: "لا ريونيون" },
  "Mayotte": { en: "Mayotte", ar: "مايوت" },
};
