export const PRACTICE_LABELS: Record<string, string> = {
  tres_pratiquant: "Très pratiquant·e",
  pratiquant: "Pratiquant·e",
  en_apprentissage: "En apprentissage",
  non_pratiquant: "Non pratiquant·e",
};

export const MARITAL_LABELS: Record<string, string> = {
  celibataire: "Célibataire",
  divorce: "Divorcé·e",
  veuf: "Veuf·ve",
};

export const GENDER_LABELS: Record<string, string> = {
  homme: "Homme",
  femme: "Femme",
};

export const BODY_TYPES = [
  "Mince",
  "Athlétique",
  "Normale",
  "Quelques rondeurs",
  "Ronde",
] as const;

export const EDUCATION_LEVELS = [
  "Sans diplôme",
  "Secondaire / Brevet",
  "Baccalauréat",
  "Bac +2",
  "Bac +3 / Licence",
  "Bac +5 / Master",
  "Doctorat",
] as const;

export const OBJECTIVES = [
  "Mariage rapide (insha'Allah)",
  "Faire connaissance pour mariage",
  "Trouver un·e partenaire sérieux·se",
  "Échanger d'abord, voir ensuite",
] as const;

export const RELIGION_OPTIONS = [
  "Islam (sunnite)",
  "Islam (chiite)",
  "Islam (autre)",
  "Islam",
] as const;

export function ageFromBirthdate(birthdate: string | null): number | null {
  if (!birthdate) return null;
  const d = new Date(birthdate);
  const diff = Date.now() - d.getTime();
  return Math.floor(diff / (365.25 * 24 * 60 * 60 * 1000));
}

/** Date maximale autorisée (18 ans révolus), recalculée à chaque appel. */
export function maxBirthdate(): string {
  const d = new Date();
  d.setFullYear(d.getFullYear() - 18);
  return d.toISOString().slice(0, 10);
}

export function minBirthdate(): string {
  const d = new Date();
  d.setFullYear(d.getFullYear() - 90);
  return d.toISOString().slice(0, 10);
}

export function isAdult(birthdate: string): boolean {
  if (!birthdate) return false;
  return birthdate <= maxBirthdate();
}

export const COUNTRIES = [
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Andorre",
  "Angola",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahreïn",
  "Bangladesh",
  "Belgique",
  "Bénin",
  "Biélorussie",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cambodge",
  "Cameroun",
  "Canada",
  "Cap-Vert",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo",
  "Congo (RDC)",
  "Corée du Sud",
  "Costa Rica",
  "Côte d'Ivoire",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Espagne",
  "Estonie",
  "Eswatini",
  "États-Unis",
  "Éthiopie",
  "Finlande",
  "France",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Guinée",
  "Guinée-Bissau",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Île Maurice",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Libéria",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Luxembourg",
  "Macédoine du Nord",
  "Madagascar",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maroc",
  "Mauritanie",
  "Mexique",
  "Moldavie",
  "Monaco",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigéria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palestine",
  "Panama",
  "Paraguay",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "Qatar",
  "République dominicaine",
  "République tchèque",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Rwanda",
  "Saint-Marin",
  "Salvador",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Thaïlande",
  "Togo",
  "Trinité-et-Tobago",
  "Tunisie",
  "Turkménistan",
  "Turquie",
  "Ukraine",
  "Uruguay",
  "Venezuela",
  "Viêt Nam",
  "Yémen",
  "Zambie",
  "Zimbabwe",
  "Autre",
] as const;

export const CITIES = [
  "Paris",
  "Marseille",
  "Lyon",
  "Toulouse",
  "Nice",
  "Nantes",
  "Montpellier",
  "Strasbourg",
  "Bordeaux",
  "Lille",
  "Rennes",
  "Reims",
  "Saint-Étienne",
  "Toulon",
  "Le Havre",
  "Grenoble",
  "Dijon",
  "Angers",
  "Nîmes",
  "Villeurbanne",
  "Clermont-Ferrand",
  "Aix-en-Provence",
  "Brest",
  "Tours",
  "Amiens",
  "Limoges",
  "Annecy",
  "Perpignan",
  "Metz",
  "Besançon",
  "Orléans",
  "Rouen",
  "Mulhouse",
  "Caen",
  "Nancy",
  "Bruxelles",
  "Anvers",
  "Liège",
  "Genève",
  "Lausanne",
  "Zurich",
  "Luxembourg",
  "Montréal",
  "Londres",
  "Madrid",
  "Barcelone",
  "Berlin",
  "Milan",
  "Rome",
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Alger",
  "Oran",
  "Tunis",
  "Dakar",
  "Abidjan",
  "Istanbul",
  "Le Caire",
  "Dubaï",
  "Doha",
  "Riyad",
  "Beyrouth",
] as const;

export const PROFESSIONS = [
  "Étudiant·e", "Santé / médical", "Enseignement / éducation",
  "Informatique / tech", "Ingénierie", "Commerce / vente", "Comptabilité / finance",
  "Droit / juridique", "Fonction publique", "Artisanat / BTP", "Transport / logistique",
  "Restauration / hôtellerie", "Entrepreneur·e / indépendant·e", "Social / associatif",
  "Sécurité", "Agriculture", "Au foyer", "Sans emploi actuellement", "Autre",
] as const;

export const ACTIVITIES_OPTIONS = [
  "Lecture / Coran", "Sport / fitness", "Voyages", "Cuisine", "Nature / randonnée",
  "Sciences islamiques", "Bénévolat / caritatif", "Arts / musique halal",
  "Technologie", "Famille / enfants", "Entrepreneuriat", "Langues",
] as const;

export const PERSONALITY_OPTIONS = [
  "Calme et posé·e",
  "Sociable et extraverti·e",
  "Réservé·e et discret·ète",
  "Organisé·e et rigoureux·se",
  "Spontané·e et aventurier·ère",
  "Sensible et empathique",
  "Ambitieux·se et déterminé·e",
  "Humoristique et joyeux·se",
] as const;