/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotreDifferenceRouteImport } from './routes/notre-difference'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as AdminResetRouteImport } from './routes/admin.reset'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AuthenticatedRechercheRouteImport } from './routes/_authenticated/recherche'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMatchsRouteImport } from './routes/_authenticated/matchs'
import { Route as AuthenticatedLikesRouteImport } from './routes/_authenticated/likes'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated/browse'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AdminSupportIndexRouteImport } from './routes/admin.support.index'
import { Route as AdminProfilesIndexRouteImport } from './routes/admin.profiles.index'
import { Route as AdminConversationsIndexRouteImport } from './routes/admin.conversations.index'
import { Route as AuthenticatedCompteIndexRouteImport } from './routes/_authenticated/compte.index'
import { Route as ApiPublicLegalDocumentsRouteImport } from './routes/api.public.legal-documents'
import { Route as AdminSupportIdRouteImport } from './routes/admin.support.$id'
import { Route as AdminProfilesIdRouteImport } from './routes/admin.profiles.$id'
import { Route as AdminConversationsPairRouteImport } from './routes/admin.conversations.$pair'
import { Route as AuthenticatedProfilePseudoRouteImport } from './routes/_authenticated/profile.$pseudo'
import { Route as AuthenticatedMessagesPseudoRouteImport } from './routes/_authenticated/messages.$pseudo'
import { Route as AuthenticatedCompteServiceClientRouteImport } from './routes/_authenticated/compte.service-client'
import { Route as AuthenticatedCompteReglesRouteImport } from './routes/_authenticated/compte.regles'
import { Route as AuthenticatedCompteProfilRouteImport } from './routes/_authenticated/compte.profil'
import { Route as AuthenticatedCompteNotificationsRouteImport } from './routes/_authenticated/compte.notifications'
import { Route as AuthenticatedCompteConfidentialiteRouteImport } from './routes/_authenticated/compte.confidentialite'
import { Route as AuthenticatedCompteCguRouteImport } from './routes/_authenticated/compte.cgu'
import { Route as AuthenticatedCompteAbonnementRouteImport } from './routes/_authenticated/compte.abonnement'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreDifferenceRoute = NotreDifferenceRouteImport.update({
  id: '/notre-difference',
  path: '/notre-difference',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/admin/visits',
  path: '/admin/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetRoute = AdminResetRouteImport.update({
  id: '/admin/reset',
  path: '/admin/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/admin/credits',
  path: '/admin/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/admin/contact',
  path: '/admin/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRechercheRoute = AuthenticatedRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchsRoute = AuthenticatedMatchsRouteImport.update({
  id: '/matchs',
  path: '/matchs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLikesRoute = AuthenticatedLikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/admin/support/',
  path: '/admin/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfilesIndexRoute = AdminProfilesIndexRouteImport.update({
  id: '/admin/profiles/',
  path: '/admin/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsIndexRoute = AdminConversationsIndexRouteImport.update({
  id: '/admin/conversations/',
  path: '/admin/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompteIndexRoute =
  AuthenticatedCompteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const ApiPublicLegalDocumentsRoute = ApiPublicLegalDocumentsRouteImport.update({
  id: '/api/public/legal-documents',
  path: '/api/public/legal-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/admin/support/$id',
  path: '/admin/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfilesIdRoute = AdminProfilesIdRouteImport.update({
  id: '/admin/profiles/$id',
  path: '/admin/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsPairRoute = AdminConversationsPairRouteImport.update({
  id: '/admin/conversations/$pair',
  path: '/admin/conversations/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilePseudoRoute =
  AuthenticatedProfilePseudoRouteImport.update({
    id: '/profile/$pseudo',
    path: '/profile/$pseudo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesPseudoRoute =
  AuthenticatedMessagesPseudoRouteImport.update({
    id: '/$pseudo',
    path: '/$pseudo',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedCompteServiceClientRoute =
  AuthenticatedCompteServiceClientRouteImport.update({
    id: '/service-client',
    path: '/service-client',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteReglesRoute =
  AuthenticatedCompteReglesRouteImport.update({
    id: '/regles',
    path: '/regles',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteProfilRoute =
  AuthenticatedCompteProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteNotificationsRoute =
  AuthenticatedCompteNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteConfidentialiteRoute =
  AuthenticatedCompteConfidentialiteRouteImport.update({
    id: '/confidentialite',
    path: '/confidentialite',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteCguRoute = AuthenticatedCompteCguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => AuthenticatedCompteRoute,
} as any)
const AuthenticatedCompteAbonnementRoute =
  AuthenticatedCompteAbonnementRouteImport.update({
    id: '/abonnement',
    path: '/abonnement',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/notre-difference': typeof NotreDifferenceRoute
  '/privacy': typeof PrivacyRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/likes': typeof AuthenticatedLikesRoute
  '/matchs': typeof AuthenticatedMatchsRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/recherche': typeof AuthenticatedRechercheRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/compte/abonnement': typeof AuthenticatedCompteAbonnementRoute
  '/compte/cgu': typeof AuthenticatedCompteCguRoute
  '/compte/confidentialite': typeof AuthenticatedCompteConfidentialiteRoute
  '/compte/notifications': typeof AuthenticatedCompteNotificationsRoute
  '/compte/profil': typeof AuthenticatedCompteProfilRoute
  '/compte/regles': typeof AuthenticatedCompteReglesRoute
  '/compte/service-client': typeof AuthenticatedCompteServiceClientRoute
  '/messages/$pseudo': typeof AuthenticatedMessagesPseudoRoute
  '/profile/$pseudo': typeof AuthenticatedProfilePseudoRoute
  '/admin/conversations/$pair': typeof AdminConversationsPairRoute
  '/admin/profiles/$id': typeof AdminProfilesIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/public/legal-documents': typeof ApiPublicLegalDocumentsRoute
  '/compte/': typeof AuthenticatedCompteIndexRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
  '/admin/profiles/': typeof AdminProfilesIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/notre-difference': typeof NotreDifferenceRoute
  '/privacy': typeof PrivacyRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/likes': typeof AuthenticatedLikesRoute
  '/matchs': typeof AuthenticatedMatchsRoute
  '/me': typeof AuthenticatedMeRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/recherche': typeof AuthenticatedRechercheRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/compte/abonnement': typeof AuthenticatedCompteAbonnementRoute
  '/compte/cgu': typeof AuthenticatedCompteCguRoute
  '/compte/confidentialite': typeof AuthenticatedCompteConfidentialiteRoute
  '/compte/notifications': typeof AuthenticatedCompteNotificationsRoute
  '/compte/profil': typeof AuthenticatedCompteProfilRoute
  '/compte/regles': typeof AuthenticatedCompteReglesRoute
  '/compte/service-client': typeof AuthenticatedCompteServiceClientRoute
  '/messages/$pseudo': typeof AuthenticatedMessagesPseudoRoute
  '/profile/$pseudo': typeof AuthenticatedProfilePseudoRoute
  '/admin/conversations/$pair': typeof AdminConversationsPairRoute
  '/admin/profiles/$id': typeof AdminProfilesIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/public/legal-documents': typeof ApiPublicLegalDocumentsRoute
  '/compte': typeof AuthenticatedCompteIndexRoute
  '/admin/conversations': typeof AdminConversationsIndexRoute
  '/admin/profiles': typeof AdminProfilesIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/notre-difference': typeof NotreDifferenceRoute
  '/privacy': typeof PrivacyRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRouteWithChildren
  '/_authenticated/likes': typeof AuthenticatedLikesRoute
  '/_authenticated/matchs': typeof AuthenticatedMatchsRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/recherche': typeof AuthenticatedRechercheRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset': typeof AdminResetRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/compte/abonnement': typeof AuthenticatedCompteAbonnementRoute
  '/_authenticated/compte/cgu': typeof AuthenticatedCompteCguRoute
  '/_authenticated/compte/confidentialite': typeof AuthenticatedCompteConfidentialiteRoute
  '/_authenticated/compte/notifications': typeof AuthenticatedCompteNotificationsRoute
  '/_authenticated/compte/profil': typeof AuthenticatedCompteProfilRoute
  '/_authenticated/compte/regles': typeof AuthenticatedCompteReglesRoute
  '/_authenticated/compte/service-client': typeof AuthenticatedCompteServiceClientRoute
  '/_authenticated/messages/$pseudo': typeof AuthenticatedMessagesPseudoRoute
  '/_authenticated/profile/$pseudo': typeof AuthenticatedProfilePseudoRoute
  '/admin/conversations/$pair': typeof AdminConversationsPairRoute
  '/admin/profiles/$id': typeof AdminProfilesIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/public/legal-documents': typeof ApiPublicLegalDocumentsRoute
  '/_authenticated/compte/': typeof AuthenticatedCompteIndexRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
  '/admin/profiles/': typeof AdminProfilesIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/notre-difference'
    | '/privacy'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/blocked'
    | '/browse'
    | '/compte'
    | '/likes'
    | '/matchs'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/recherche'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/contact'
    | '/admin/credits'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/visits'
    | '/admin/'
    | '/compte/abonnement'
    | '/compte/cgu'
    | '/compte/confidentialite'
    | '/compte/notifications'
    | '/compte/profil'
    | '/compte/regles'
    | '/compte/service-client'
    | '/messages/$pseudo'
    | '/profile/$pseudo'
    | '/admin/conversations/$pair'
    | '/admin/profiles/$id'
    | '/admin/support/$id'
    | '/api/public/legal-documents'
    | '/compte/'
    | '/admin/conversations/'
    | '/admin/profiles/'
    | '/admin/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/notre-difference'
    | '/privacy'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/blocked'
    | '/browse'
    | '/likes'
    | '/matchs'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/recherche'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/contact'
    | '/admin/credits'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/visits'
    | '/admin'
    | '/compte/abonnement'
    | '/compte/cgu'
    | '/compte/confidentialite'
    | '/compte/notifications'
    | '/compte/profil'
    | '/compte/regles'
    | '/compte/service-client'
    | '/messages/$pseudo'
    | '/profile/$pseudo'
    | '/admin/conversations/$pair'
    | '/admin/profiles/$id'
    | '/admin/support/$id'
    | '/api/public/legal-documents'
    | '/compte'
    | '/admin/conversations'
    | '/admin/profiles'
    | '/admin/support'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mot-de-passe-oublie'
    | '/notre-difference'
    | '/privacy'
    | '/reinitialiser-mot-de-passe'
    | '/sitemap.xml'
    | '/_authenticated/blocked'
    | '/_authenticated/browse'
    | '/_authenticated/compte'
    | '/_authenticated/likes'
    | '/_authenticated/matchs'
    | '/_authenticated/me'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/recherche'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/config'
    | '/admin/contact'
    | '/admin/credits'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/reports'
    | '/admin/reset'
    | '/admin/visits'
    | '/admin/'
    | '/_authenticated/compte/abonnement'
    | '/_authenticated/compte/cgu'
    | '/_authenticated/compte/confidentialite'
    | '/_authenticated/compte/notifications'
    | '/_authenticated/compte/profil'
    | '/_authenticated/compte/regles'
    | '/_authenticated/compte/service-client'
    | '/_authenticated/messages/$pseudo'
    | '/_authenticated/profile/$pseudo'
    | '/admin/conversations/$pair'
    | '/admin/profiles/$id'
    | '/admin/support/$id'
    | '/api/public/legal-documents'
    | '/_authenticated/compte/'
    | '/admin/conversations/'
    | '/admin/profiles/'
    | '/admin/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NotreDifferenceRoute: typeof NotreDifferenceRoute
  PrivacyRoute: typeof PrivacyRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetRoute: typeof AdminResetRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConversationsPairRoute: typeof AdminConversationsPairRoute
  AdminProfilesIdRoute: typeof AdminProfilesIdRoute
  AdminSupportIdRoute: typeof AdminSupportIdRoute
  ApiPublicLegalDocumentsRoute: typeof ApiPublicLegalDocumentsRoute
  AdminConversationsIndexRoute: typeof AdminConversationsIndexRoute
  AdminProfilesIndexRoute: typeof AdminProfilesIndexRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-difference': {
      id: '/notre-difference'
      path: '/notre-difference'
      fullPath: '/notre-difference'
      preLoaderRoute: typeof NotreDifferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/admin/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset': {
      id: '/admin/reset'
      path: '/admin/reset'
      fullPath: '/admin/reset'
      preLoaderRoute: typeof AdminResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/admin/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recherche': {
      id: '/_authenticated/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof AuthenticatedRechercheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matchs': {
      id: '/_authenticated/matchs'
      path: '/matchs'
      fullPath: '/matchs'
      preLoaderRoute: typeof AuthenticatedMatchsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/likes': {
      id: '/_authenticated/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof AuthenticatedLikesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/admin/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profiles/': {
      id: '/admin/profiles/'
      path: '/admin/profiles'
      fullPath: '/admin/profiles/'
      preLoaderRoute: typeof AdminProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations/': {
      id: '/admin/conversations/'
      path: '/admin/conversations'
      fullPath: '/admin/conversations/'
      preLoaderRoute: typeof AdminConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte/': {
      id: '/_authenticated/compte/'
      path: '/'
      fullPath: '/compte/'
      preLoaderRoute: typeof AuthenticatedCompteIndexRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/api/public/legal-documents': {
      id: '/api/public/legal-documents'
      path: '/api/public/legal-documents'
      fullPath: '/api/public/legal-documents'
      preLoaderRoute: typeof ApiPublicLegalDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/admin/support/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profiles/$id': {
      id: '/admin/profiles/$id'
      path: '/admin/profiles/$id'
      fullPath: '/admin/profiles/$id'
      preLoaderRoute: typeof AdminProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations/$pair': {
      id: '/admin/conversations/$pair'
      path: '/admin/conversations/$pair'
      fullPath: '/admin/conversations/$pair'
      preLoaderRoute: typeof AdminConversationsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/$pseudo': {
      id: '/_authenticated/profile/$pseudo'
      path: '/profile/$pseudo'
      fullPath: '/profile/$pseudo'
      preLoaderRoute: typeof AuthenticatedProfilePseudoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$pseudo': {
      id: '/_authenticated/messages/$pseudo'
      path: '/$pseudo'
      fullPath: '/messages/$pseudo'
      preLoaderRoute: typeof AuthenticatedMessagesPseudoRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/compte/service-client': {
      id: '/_authenticated/compte/service-client'
      path: '/service-client'
      fullPath: '/compte/service-client'
      preLoaderRoute: typeof AuthenticatedCompteServiceClientRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/regles': {
      id: '/_authenticated/compte/regles'
      path: '/regles'
      fullPath: '/compte/regles'
      preLoaderRoute: typeof AuthenticatedCompteReglesRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/profil': {
      id: '/_authenticated/compte/profil'
      path: '/profil'
      fullPath: '/compte/profil'
      preLoaderRoute: typeof AuthenticatedCompteProfilRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/notifications': {
      id: '/_authenticated/compte/notifications'
      path: '/notifications'
      fullPath: '/compte/notifications'
      preLoaderRoute: typeof AuthenticatedCompteNotificationsRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/confidentialite': {
      id: '/_authenticated/compte/confidentialite'
      path: '/confidentialite'
      fullPath: '/compte/confidentialite'
      preLoaderRoute: typeof AuthenticatedCompteConfidentialiteRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/cgu': {
      id: '/_authenticated/compte/cgu'
      path: '/cgu'
      fullPath: '/compte/cgu'
      preLoaderRoute: typeof AuthenticatedCompteCguRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/abonnement': {
      id: '/_authenticated/compte/abonnement'
      path: '/abonnement'
      fullPath: '/compte/abonnement'
      preLoaderRoute: typeof AuthenticatedCompteAbonnementRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
  }
}

interface AuthenticatedCompteRouteChildren {
  AuthenticatedCompteAbonnementRoute: typeof AuthenticatedCompteAbonnementRoute
  AuthenticatedCompteCguRoute: typeof AuthenticatedCompteCguRoute
  AuthenticatedCompteConfidentialiteRoute: typeof AuthenticatedCompteConfidentialiteRoute
  AuthenticatedCompteNotificationsRoute: typeof AuthenticatedCompteNotificationsRoute
  AuthenticatedCompteProfilRoute: typeof AuthenticatedCompteProfilRoute
  AuthenticatedCompteReglesRoute: typeof AuthenticatedCompteReglesRoute
  AuthenticatedCompteServiceClientRoute: typeof AuthenticatedCompteServiceClientRoute
  AuthenticatedCompteIndexRoute: typeof AuthenticatedCompteIndexRoute
}

const AuthenticatedCompteRouteChildren: AuthenticatedCompteRouteChildren = {
  AuthenticatedCompteAbonnementRoute: AuthenticatedCompteAbonnementRoute,
  AuthenticatedCompteCguRoute: AuthenticatedCompteCguRoute,
  AuthenticatedCompteConfidentialiteRoute:
    AuthenticatedCompteConfidentialiteRoute,
  AuthenticatedCompteNotificationsRoute: AuthenticatedCompteNotificationsRoute,
  AuthenticatedCompteProfilRoute: AuthenticatedCompteProfilRoute,
  AuthenticatedCompteReglesRoute: AuthenticatedCompteReglesRoute,
  AuthenticatedCompteServiceClientRoute: AuthenticatedCompteServiceClientRoute,
  AuthenticatedCompteIndexRoute: AuthenticatedCompteIndexRoute,
}

const AuthenticatedCompteRouteWithChildren =
  AuthenticatedCompteRoute._addFileChildren(AuthenticatedCompteRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesPseudoRoute: typeof AuthenticatedMessagesPseudoRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesPseudoRoute: AuthenticatedMessagesPseudoRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRouteWithChildren
  AuthenticatedLikesRoute: typeof AuthenticatedLikesRoute
  AuthenticatedMatchsRoute: typeof AuthenticatedMatchsRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRechercheRoute: typeof AuthenticatedRechercheRoute
  AuthenticatedProfilePseudoRoute: typeof AuthenticatedProfilePseudoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRouteWithChildren,
  AuthenticatedLikesRoute: AuthenticatedLikesRoute,
  AuthenticatedMatchsRoute: AuthenticatedMatchsRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRechercheRoute: AuthenticatedRechercheRoute,
  AuthenticatedProfilePseudoRoute: AuthenticatedProfilePseudoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NotreDifferenceRoute: NotreDifferenceRoute,
  PrivacyRoute: PrivacyRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminContactRoute: AdminContactRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetRoute: AdminResetRoute,
  AdminVisitsRoute: AdminVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConversationsPairRoute: AdminConversationsPairRoute,
  AdminProfilesIdRoute: AdminProfilesIdRoute,
  AdminSupportIdRoute: AdminSupportIdRoute,
  ApiPublicLegalDocumentsRoute: ApiPublicLegalDocumentsRoute,
  AdminConversationsIndexRoute: AdminConversationsIndexRoute,
  AdminProfilesIndexRoute: AdminProfilesIndexRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
